using System.Collections.Generic;
using System.Threading.Tasks;

namespace IntelliGrade.App.Interfaces;

/// <summary>
/// Service for managing course and assignment files and directories.
/// </summary>
public interface IFileManagerService
{
    /// <summary>
    /// Gets all available courses from the rubric directory.
    /// </summary>
    /// <param name="rubricDir">Root rubric directory path</param>
    /// <returns>List of course names</returns>
    List<string> GetCourses(string rubricDir);

    /// <summary>
    /// Gets all assignments for a specific course and language.
    /// </summary>
    /// <param name="rubricDir">Root rubric directory path</param>
    /// <param name="course">Course name</param>
    /// <param name="language">Programming language</param>
    /// <returns>List of assignment names</returns>
    List<string> GetAssignments(string rubricDir, string course, string language);

    /// <summary>
    /// Reads rubric content from file.
    /// </summary>
    /// <param name="rubricPath">Path to rubric file</param>
    /// <returns>Rubric content or null if not found</returns>
    string? ReadRubric(string rubricPath);

    /// <summary>
    /// Finds output files generated by program execution.
    /// </summary>
    /// <param name="directory">Directory to search</param>
    /// <param name="copiedFiles">Files to exclude from search</param>
    /// <returns>List of output file names</returns>
    List<string> FindOutputFiles(string directory, List<string> copiedFiles);

    /// <summary>
    /// Deletes specified files from directory.
    /// </summary>
    /// <param name="directory">Target directory</param>
    /// <param name="filesToRemove">List of file names to delete</param>
    void CleanupFiles(string directory, List<string> filesToRemove);

    /// <summary>
    /// Clones a git repository to the target directory.
    /// </summary>
    /// <param name="repoUrl">Repository URL</param>
    /// <param name="targetDirectory">Destination directory</param>
    /// <returns>Error message or null if successful</returns>
    Task<string?> CloneGitRepository(string repoUrl, string targetDirectory);
}
