using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using IntelliGrade.App.Interfaces;

namespace IntelliGrade.App.Services;

/// <summary>
/// Manages file operations for assignments, rubrics, and student submissions.
/// </summary>
public class FileManagerService : IFileManagerService
{
    /// <summary>
    /// Gets all course directories from the rubric directory.
    /// Creates the directory if it doesn't exist.
    /// </summary>
    /// <param name="rubricDir">Path to rubric directory</param>
    /// <returns>List of course names</returns>
    public List<string> GetCourses(string rubricDir)
    {
        if (!Directory.Exists(rubricDir))
        {
            Directory.CreateDirectory(rubricDir);
            return new List<string>();
        }

        return Directory.GetDirectories(rubricDir)
            .Select(Path.GetFileName)
            .Where(name => !string.IsNullOrEmpty(name))
            .Cast<string>()
            .OrderBy(name => name)
            .ToList();
    }

    /// <summary>
    /// Gets all assignment rubrics for a specific course and language.
    /// Supports both .txt and .json rubric file formats.
    /// </summary>
    /// <param name="rubricDir">Path to rubric directory</param>
    /// <param name="course">Course name</param>
    /// <param name="language">Programming language</param>
    /// <returns>List of assignment names (without extensions)</returns>
    public List<string> GetAssignments(string rubricDir, string course, string language)
    {
        var path = Path.Combine(rubricDir, course, language);

        if (!Directory.Exists(path))
        {
            Directory.CreateDirectory(path);
            return new List<string>();
        }

        // Support both .txt and .json rubric files
        var txtFiles = Directory.GetFiles(path, "*.txt");
        var jsonFiles = Directory.GetFiles(path, "*.json");

        return txtFiles.Concat(jsonFiles)
            .Select(f => Path.GetFileNameWithoutExtension(f))
            .Where(name => !string.IsNullOrEmpty(name))
            .Cast<string>()
            .Distinct()
            .OrderBy(name => name)
            .ToList();
    }

    /// <summary>
    /// Reads rubric content from a file.
    /// </summary>
    /// <param name="rubricPath">Full path to rubric file</param>
    /// <returns>Rubric content as string, or null if file doesn't exist</returns>
    public string? ReadRubric(string rubricPath)
    {
        return File.Exists(rubricPath) ? File.ReadAllText(rubricPath) : null;
    }

    /// <summary>
    /// Finds output files generated by student programs.
    /// Excludes source code files and searches for recently modified files.
    /// </summary>
    /// <param name="directory">Directory to search</param>
    /// <param name="copiedFiles">Files to exclude from search</param>
    /// <returns>List of output file names</returns>
    public List<string> FindOutputFiles(string directory, List<string> copiedFiles)
    {
        var outputFiles = new List<string>();
        var excludeExtensions = new[] { ".cs", ".py", ".java", ".cpp", ".c", ".rs", ".go", ".rb", ".php", ".js" };

        // Find files modified in the last 5 minutes (likely program outputs)
        var allFiles = Directory.GetFiles(directory)
            .Where(f => !excludeExtensions.Contains(Path.GetExtension(f).ToLower()))
            .Where(f => File.GetLastWriteTime(f) > DateTime.Now.AddMinutes(-5))
            .Where(f => !copiedFiles.Contains(Path.GetFileName(f)));

        return allFiles.Select(Path.GetFileName)
            .Where(name => !string.IsNullOrEmpty(name))
            .Cast<string>()
            .ToList();
    }

    /// <summary>
    /// Deletes specified files from a directory.
    /// </summary>
    /// <param name="directory">Directory containing files to delete</param>
    /// <param name="filesToRemove">List of file names to delete</param>
    public void CleanupFiles(string directory, List<string> filesToRemove)
    {
        foreach (var file in filesToRemove)
        {
            var fullPath = Path.Combine(directory, file);
            if (File.Exists(fullPath))
            {
                File.Delete(fullPath);
            }
        }
    }

    /// <summary>
    /// Clones a Git repository to a target directory.
    /// </summary>
    /// <param name="repoUrl">Git repository URL</param>
    /// <param name="targetDirectory">Target directory for cloned repository</param>
    /// <returns>Error message if failed, null if successful</returns>
    public async System.Threading.Tasks.Task<string?> CloneGitRepository(string repoUrl, string targetDirectory)
    {
        try
        {
            var processInfo = new System.Diagnostics.ProcessStartInfo
            {
                FileName = "git",
                Arguments = $"clone {repoUrl} \"{targetDirectory}\"",
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            };

            using var process = System.Diagnostics.Process.Start(processInfo);
            if (process == null)
                return "Failed to start git process";

            await process.WaitForExitAsync();

            if (process.ExitCode == 0)
                return null;

            var error = await process.StandardError.ReadToEndAsync();
            return string.IsNullOrWhiteSpace(error) ? "Git clone failed" : error;
        }
        catch (Exception ex)
        {
            return $"Error cloning repository: {ex.Message}";
        }
    }
}